### ISSUE TITLE
Update stringtable/fix grammar errors

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/HeartsAndMindsTFR#11]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L2

**Comment by the-pope-himself** [comment]
This is fixed in the current pull request.

**Comment by Grewsome2018** [comment]
Resolved in #17
