### ISSUE TITLE
Stringtable Updates

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/HeartsAndMindsTFR#12]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1929

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1795

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1781

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1565

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1558

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1537

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1530

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1523

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1453

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1081

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L1051

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L991

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L910

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L866

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L829

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L799

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L769

https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/stringtable.xml#L13

**Comment by the-pope-himself** [comment]
This is fixed in the current pull request.

**Comment by Grewsome2018** [comment]
Resolved in #17
