### ISSUE TITLE
Mission save to DB

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/HeartsAndMindsTFR#15]
Logged admin has a self interaction that allows them to save the mission to DB when ever they chose to.

I noticed there was also a param to set auto save to occur every 1 hr, 2 hr,  3 hr etc etc
It mentions that this could be immersion breaking. How? ? ?

**Comment by Grewsome2018** [comment]
This should probably be turned on less someone forgets to save before restart

**Comment by Grewsome2018** [comment]
Fixed in #30
