### ISSUE TITLE
Who can access zeus? 

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/HeartsAndMindsTFR#16]
Is it worth setting up a white list system similar to the lib commander slot for those who should be eligible to take the officer slot.
Give the slot a zeus module tied to that role.

As an extension of this could the admins be added to a list of UID'S to have zeus and officer role perms?

**Comment by Grewsome2018** [comment]
Can definitely add a zeus module that gives the admin UID's access to zeus. I don't know about the officer role and how it works though

**Comment by Grewsome2018** [comment]
https://github.com/Task-Force-Raider/Liberation-Livonia/blob/50761e1cecd26a290d039891f44ff23347419296/kp_liberation.Enoch/whitelist.sqf#L13

Has the Steam UID's there

**Comment by Grewsome2018** [comment]
Semi resolved in #23

**Comment by Grewsome2018** [comment]
This may require a script as the Zeus modules don't pick up UID's after disconnect

**Comment by McFurSun** [comment]
this may help, although its not UID's 
https://forums.bohemia.net/forums/topic/201110-zeus-jip-problem/?do=findComment&comment=3138258

**Comment by Grewsome2018** [comment]
https://steamcommunity.com/app/107410/discussions/17/1471966894887720536/

will need to be resolved before v1

**Comment by Grewsome2018** [comment]
Fixed in #45
