### ISSUE TITLE
QRF in veh_killed.sqf

### ISSUE THREAD

**Issue by the-pope-himself** [Task-Force-Raider/HeartsAndMindsTFR#36]
Occasionally one of the two technicals that spawn in as QRF once a vehicle is downed will not want to path correctly to the waypoint.

This is due to veh_killed.sqf being an event handler and as such, a sleep code cannot be used to ensure both vehicles are spawned in before the waypoint is given. There is a way around it by spawning in two lots of empty vehicles, then two squads and finally waypointing from there but this is a long way around to get a similar effect. 

Ultimately I think the benefit vs time cost isn't worth it as the QRF works most of the time.

**Comment by BroBeansCPG** [comment]
Consider it a randomisation feature

**Comment by McFurSun** [comment]
When I can finally get on the PC I can try implement the send fnc.
