### ISSUE TITLE
Make container smaller

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/HeartsAndMindsTFR#38]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/c93ef0df0c8d5ff4de9f27f565603a36003ee4d2/core/def/mission.sqf#L275

**Comment by Grewsome2018** [comment]
And slingable

**Comment by BroBeansCPG** [comment]
Added: 

Bug where no item spawned via the logistics point is slingable. 
- requires more testing.

**Comment by Grewsome2018** [comment]
And to throw it on a van or something

**Comment by McFurSun** [comment]
Maybe it's intended to not be singable.
That way you have to drive through bandit country to get it where you need it

Also if we

**Comment by Grewsome2018** [comment]
Yeah but it’s far too big to be put in a van or even on a flatbed we were testing it yesterday and it was fuckedy so either we make it smaller and change the object it uses or we enable it to be slung

**Comment by BroBeansCPG** [comment]
I vote for a smaller container so we can still transport on the ground

**Comment by Grewsome2018** [comment]
Resolved in #44
