### ISSUE TITLE
Respawn with loadouts

### ISSUE THREAD

**Issue by BroBeansCPG** [Task-Force-Raider/HeartsAndMindsTFR#39]
Minor QOL considering you spawn next to arsenal box anyway but doesn’t take much work regardless.

**Comment by Grewsome2018** [comment]
onPlayerKilled.sqf:

`player setVariable ["Saved_Loadout",getUnitLoadout player];`

onPlayerRespawn.sqf:

`player setUnitLoadout (player getVariable ["Saved_Loadout",[]]);`

thoughts?

**Comment by Grewsome2018** [comment]
Resolved in #44
