### ISSUE TITLE
Add perimeter patrols

### ISSUE THREAD

**Issue by BroBeansCPG** [Task-Force-Raider/HeartsAndMindsTFR#43]
Add friendly perimeter patrols around the airbase to repel enemy attacks. 

We could leave these out to create an alternative dynamic of defending/patrolling.

**Comment by Grewsome2018** [comment]
This is a tough one, we don't want to make it so we always have to have someone at base monitoring everything ALTHOUGH I also don't want to have AI doing half a job (which is protecting our shit)

**Comment by BroBeansCPG** [comment]
I think if the arsenal box wasn’t so exposed it wouldn’t be a problem. But considering you might have new players gearing up and a techie snipes them from one side of the airfield.. 

Isn’t exactly a warm welcome. 

I do however like the dynamic of occasional base patrols like we did the other night

**Comment by Grewsome2018** [comment]
1x marine squad patrols eastern side of airbase.
US Army forces on gates are set to engage enemy targets although they can not move.
