### ISSUE TITLE
Change type of FOB building

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/HeartsAndMindsTFR#48]
https://github.com/Vdauphin/HeartsAndMinds/blob/d680700ce496456dcca4fa5ea3009f2c7f72e8f7/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L254

Currently is an HQ building.
Could change to something more in keeping with the terrain and a smaller size so we can deploy it at the already existing FOB's.

Will need to be destructible as the FOB is removed if overrun/destroyed.

Could look to change the flag to the TFR one as well.

And change the size of the crate used to deploy it.

**Comment by Grewsome2018** [comment]
Done
