### ISSUE TITLE
Pre Packaged Kits

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/HeartsAndMindsTFR#49]
With the new CBRN gameplay aspect it could be handy to have boxes or vehicles with all the required items already in them.
Just grab the box or vehicle and you have all you need to get the job done.
The same could be done to cover EOD.

Issues:
- does the box return to base on mission restart
- does the vehicle inventory return on mission restart
- does the inventory return on repair of vehicle wreck
- are all required items able to be stored in boxes or vehicles

**Comment by Grewsome2018** [comment]
To answer the bulletpoints

- No, it will physically be where it is at time of database save (exception - if it is in a cargo space of a vehicle, it'll still be in that cargo space (as a virtual object that can be unloaded to be physically interacted with))

- No, the inventory won't refill itself automatically without a code I imagine

- Unlikely as the container will not be considered a "vehicle"

- All required items seem to be able to be stored in a vehicle cargo space within a container

**Comment by Grewsome2018** [comment]
CBRN added
