### ISSUE TITLE
Add timed marker to mark cache after X amount of time

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/HeartsAndMindsTFR#5]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/core/fnc/cache/find_pos.sqf#L47

**Comment by the-pope-himself** [comment]
This has been included in Pull Request #34.

**Comment by Grewsome2018** [comment]
Resolved in #34
