### ISSUE TITLE
Add ACEX Fortification module to mission.sqm

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/HeartsAndMindsTFR#51]
Enz Zziio 12/01/20 at 9:21 PM
SUGGESTION FOR NEXT UPDATE: include acex fortification module

**Comment by Grewsome2018** [comment]
Will potentially require a DB wipe to update mission.sqm

**Comment by McFurSun** [comment]
I don't think we have progressed to far, or whether it would be noticeable.

**Comment by Grewsome2018** [comment]
Will wipe and restart mission at a slightly higher reputation rate

**Comment by Grewsome2018** [comment]
ACEX modules added with small medium and large presets
