### ISSUE TITLE
Add ACRE GSM Antenna to list of spawn-able buildings.

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/HeartsAndMindsTFR#52]
Add this so they can be spawned, moved to location and placed and persist.
Saves a Zeus having to do it.

Issues:
- could a player wreck its persistence by packing it and then rebuilding elsewhere
- how would it get transported from the logi point?

**Comment by McFurSun** [comment]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/667d73a3e2c550c69c8d509f921ac344eb96cd5a/core/def/mission.sqf#L366

GS "vhf30108spike" (without mast)
GSM"vhf30108Item" (with mast)

**Comment by Grewsome2018** [comment]
What are antenna class names?

**Comment by McFurSun** [comment]
"vhf30108spike"
"vhf30108Item"

**Comment by Grewsome2018** [comment]
Will add tomorrow

**Comment by Grewsome2018** [comment]
Added
