### ISSUE TITLE
Adjust hideout compositions (smaller??)

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/HeartsAndMindsTFR#8]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/core/fnc/mil/create_hideout_composition.sqf#L3

**Comment by the-pope-himself** [comment]
Do they need to be adjusted to fit a smaller area or adjusted to just have less objects? Or both?

**Comment by Grewsome2018** [comment]
Potentially both to make them more difficult to find was my idea initially

**Comment by the-pope-himself** [comment]
This has been adjusted in Pull Request #34.

There is still an issue with the compositions sometimes spawning objects that look out of place...for example a jet engine air starter, but I'm having trouble finding where he keeps the list of objects to pull from.

**Comment by McFurSun** [comment]
Once a mission starts maybe the hideouts all spawn and don't change.
Then we could potentially find them with zeus and customise them in game.
It would be interesting to see if moving them large distances affects them. Ie moving them to better locations.

**Comment by Grewsome2018** [comment]
Resolved in #35
