### ISSUE TITLE
Incorporate SEND script with crashed heli script

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/HeartsAndMindsTFR#9]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/4656025e449acd043f0b8d248b60a97fd4f13b44/core/fnc/mil/send.sqf#L6

**Comment by Grewsome2018** [comment]
My thoughts are that when a helicopter goes down and the marker is created on the map highlighting where the wreck is, we see if we can get the send script to assign a group to patrol to it and secure it

**Comment by the-pope-himself** [comment]
This has been included in Pull Request #34.

**Comment by McFurSun** [comment]
https://github.com/Task-Force-Raider/HeartsAndMindsTFR/blob/922479cbe602ecbcc5167976d0725540df4fc68f/core/fnc/eh/veh_killed.sqf#L6

I think this is where we want to call the send function @Grewsome2018 mentioned.

**Comment by Grewsome2018** [comment]
Resolved in #35
